import sys
from datetime import datetime

class CodeAssembler:
    def __init__(ca) -> None:
        ca.defTabSize = 4
        ca.body = [] 
        ca.tabSize = 0

    def insert(ca, line: str = ''):
        line = (ca.tabSize * " ") + line + "\n"
        ca.body.append(line);

    def dedent(ca):
        if (ca.tabSize > 0):
            ca.tabSize -= ca.defTabSize

    def indent(ca):
        ca.tabSize += ca.defTabSize

    def __str__(ca) -> str:
        return ''.join(ca.body)

def defineAst(outDir: str, baseClass: str, types: list[str]):
    outPath = "./" + outDir + '/' + baseClass + '.h'

    print("writing to", outPath)
    Cpp = CodeAssembler()
    Cpp.insert("//") 
    Cpp.insert(f"// {baseClass}.h")
    Cpp.insert("// Croix")
    Cpp.insert("//")
    day = datetime.today().strftime('%Y-%m-%d')
    Cpp.insert(f"// Generated by Joshua Pepple on {day}.")
    Cpp.insert("//")
    Cpp.insert()
    Cpp.insert(f"#ifndef {baseClass}_h")
    Cpp.insert(f"#define {baseClass}_h")
    Cpp.insert()

    Cpp.insert("#include <iostream>")
    Cpp.insert("#include <string>")
    Cpp.insert()
    Cpp.insert("using namespace std;")
    
    Cpp.insert()
    Cpp.insert(f"class {baseClass} " + "{")

    for t in types:
        Cpp.insert()
        className = t.split(':')[0].strip()
        fields = t.split(':')[1].strip()
        defineType(Cpp, baseClass, className, fields)
    Cpp.insert("};")
    Cpp.insert()
    Cpp.insert(f"#endif /* {baseClass}_h */")
    
    print(Cpp)

def defineType(CA: CodeAssembler, baseClass: str, className: str, fieldList: str):
    # start of new class 
    CA.indent()
    CA.insert(f"class {className} : public {baseClass} " + "{")

    CA.insert("public:")
    # indent into definition of class
    CA.indent()
    # constructor
    CA.insert(f"{className} ({fieldList}) " + "{")
    # constructor body
    CA.indent()
    fields = fieldList.split(', ')
    for f in fields:
        varName = f.split(" ")[1]
        CA.insert(f"this.{varName} = {varName};")
    CA.dedent()

    CA.insert("}")
    CA.dedent()

    CA.insert()
    CA.insert("private:")
    # write private members
    CA.indent()
    for f in fields:
        CA.insert(f+';')
    CA.dedent()
    CA.insert("};")
    CA.dedent()
    

argc = len(sys.argv)
if (argc != 2):
    print("usage: py gen_ast.py <output_dir>")
    exit(64) # exit with wrong usage error

dest = sys.argv[1]

types = [
    "Binary    :  Expr left, Token operator, Expr right",
    "Grouping  :  Expr expr",
    "Boolean   :  bool value",
    "Number    :  double value",
    "String    :  string value"
]

defineAst(dest, "Expr", types)